version: '2'
services:
  # testsuite:
  #   image: php:7.4.10-cli
  #   working_dir: /code
  #   command: ["php", "testsuite.php"]
  #   volumes:
  #     - ./www/tests:/code:ro
  #   depends_on:
  #     - caddy
  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - "8080:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - php-fpm
  httpd:
    image: php:7.4.10-apache
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html:ro
  nginx:
    image: nginx:1.19.2-alpine
    ports:
        - "8082:80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.4.10-fpm
    expose:
      - 9000
    volumes:
      - ./www:/usr/share/caddy:ro
      - ./www:/usr/share/nginx/html:ro
