version: '2'

services:
  # testsuite:
  #   image: php:7.4.10-cli
  #   working_dir: /code
  #   command: ["php", "testsuite.php"]
  #   volumes:
  #     - ./www/tests:/code:ro
  #   depends_on:
  #     - caddy
  caddy-v211:
    image: caddy:2.1.1-alpine
    ports:
      - "8080:80"
    volumes:
      - ./caddy/Caddyfile2:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:ro
    depends_on:
      - php-fpm
  caddy-v211-custom-config:
    image: caddy:2.1.1-alpine
    ports:
      - "8083:80"
    volumes:
      - ./caddy/Caddyfile1:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:ro
    depends_on:
      - php-fpm
  caddy-v211-pr3739:
    image: caddy:2.1.1-alpine
    ports:
      - "8084:80"
    volumes:
      - ./caddy/Caddyfile2:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:ro
      - ./caddy/bin/caddy_Linux_go1.14_3e577ef:/usr/bin/caddy:ro
    depends_on:
      - php-fpm
  httpd:
    # To use mod_rewrite we need to build our own image - no ENV VAR to enable an Apache module. 
    # image: php:7.4.10-apache
    build:
      context: ./apache
      args:
        - PHP_APACHE_IMAGE=7.4.10-apache
    image: php:7.4.10-apache-mod-rewrite-enabled
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html:ro
  nginx:
    image: nginx:1.19.2-alpine
    ports:
        - "8082:80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.4.10-fpm
    expose:
      - 9000
    volumes:
      - ./www:/usr/share/caddy:ro
      - ./www:/usr/share/nginx/html:ro
